ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# ARG DEBIAN_FRONTEND=noninteractive
# ENV ROS_DISTRO=jazzy
# ENV ROS_ROOT=/opt/ros/${ROS_DISTRO}

# Install prebuilt packages
# COPY . /workspaces/isaac_ros-dev
# RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
#     apt-get update \
#     && bash scripts/setup_workspace.sh