[project]
name = "diffusion-robot-test-ws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nvidia-curobo[cu13-torch]",
    "torchvision", # Χρειάζεται καθώς το nvblox_torch εξαρτάται από αυτό
    "nvblox_torch",
]

[tool.uv]
workspace = { members = ["external/curobo"] }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true


[tool.uv.sources]
nvidia-curobo = { workspace = true }
torch = [
  { index = "pytorch-cu130" }
]
torchvision = [
  { index = "pytorch-cu130" }
]
nvblox_torch = { url = "https://github.com/nvidia-isaac/nvblox/releases/download/v0.0.10/nvblox_torch-0.0.10+cu13ubuntu24-py3-none-linux_x86_64.whl" }
