[project]
name = "diffusion-robot-test-ws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torchvision", # Χρειάζεται καθώς το nvblox_torch εξαρτάται από αυτό
    "nvblox_torch",
    "catkin-pkg>=1.1.0",
    "empy==3.3.4",
    "lark>=1.3.1",
    "pyyaml>=6.0.3",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true


[tool.uv.sources]
torch = [
  { index = "pytorch-cu130" }
]
torchvision = [
  { index = "pytorch-cu130" }
]
nvblox_torch = { url = "https://github.com/nvidia-isaac/nvblox/releases/download/v0.0.10/nvblox_torch-0.0.10+cu13ubuntu24-py3-none-linux_x86_64.whl" }
