move_group:
  ros__parameters:
    # ── Planning Pipelines ──────────────────────────────
    planning_pipelines:
      - ompl
    default_planning_pipeline: ompl
    default_workspace_bounds: 10.0

    # ── Octomap / 3D Perception ─────────────────────────
    octomap_frame: world
    octomap_resolution: 0.05
    max_range: 3.0

    # ── OMPL Pipeline ───────────────────────────────────
    ompl:
      planning_plugins:
        - ompl_interface/OMPLPlanner
      request_adapters:
        - default_planning_request_adapters/ResolveConstraintFrames
        - default_planning_request_adapters/ValidateWorkspaceBounds
        - default_planning_request_adapters/CheckStartStateBounds
        - default_planning_request_adapters/CheckStartStateCollision
      response_adapters:
        - default_planning_response_adapters/AddTimeOptimalParameterization
        - default_planning_response_adapters/ValidateSolution
        - default_planning_response_adapters/DisplayMotionPath
      start_state_max_bounds_error: 0.1

      planner_configs:
        SBLkConfigDefault:
          type: geometric::SBL
          range: 0.0
        LBKPIECEkConfigDefault:
          type: geometric::LBKPIECE
          range: 0.0
        RRTkConfigDefault:
          type: geometric::RRT
          range: 0.0
        RRTConnectkConfigDefault:
          type: geometric::RRTConnect
          range: 0.0

      lift:
        planner_configs:
          - RRTConnectkConfigDefault
          - RRTkConfigDefault
          - SBLkConfigDefault
          - LBKPIECEkConfigDefault
        longest_valid_segment_fraction: 0.005
      ur:
        planner_configs:
          - RRTConnectkConfigDefault
          - RRTkConfigDefault
          - SBLkConfigDefault
          - LBKPIECEkConfigDefault
        longest_valid_segment_fraction: 0.005
      all:
        planner_configs:
          - RRTConnectkConfigDefault
          - RRTkConfigDefault
          - SBLkConfigDefault
          - LBKPIECEkConfigDefault
        longest_valid_segment_fraction: 0.005
